CREATE TABLE IF NOT EXISTS rsvp_responses (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name VARCHAR(200) NOT NULL,
    email VARCHAR(200) NOT NULL,
    attending VARCHAR(100) NOT NULL,
    plus_one VARCHAR(200) NOT NULL DEFAULT '',
    meal VARCHAR(100) NOT NULL DEFAULT '',
    message TEXT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
